import React, { useState } from 'react';
import { Incident } from '../types';
import { TRIGGERS } from '../constants';
import { Button } from '../components/ui/Button';
import { getBehaviorAnalysis } from '../services/geminiService';
import { Plus, BarChart2, Calendar, BrainCircuit, Trash2, Pencil, FileDown } from 'lucide-react';
import { BottomSheet } from '../components/BottomSheet';
import { BarChart, Bar, XAxis, Tooltip, ResponsiveContainer, Cell } from 'recharts';
import { useIncidents } from '../services/db';
import jsPDF from 'jspdf';
import { shouldPromptReview, requestAppReview, markReviewPrompted } from '../services/appReview';

interface BehaviorLogProps {
  petName: string;
  petId?: string | null;
}

export const BehaviorLog: React.FC<BehaviorLogProps> = ({ petName, petId }) => {
  const { incidents, hasMore, loadMore, addIncident, updateIncident, deleteIncident } = useIncidents(petId);
  const [showAddModal, setShowAddModal] = useState(false);
  const [editingIncident, setEditingIncident] = useState<Incident | null>(null);
  const [aiAnalysis, setAiAnalysis] = useState<string | null>(null);
  const [isAnalyzing, setIsAnalyzing] = useState(false);

  // New Incident Form State
  const [newSeverity, setNewSeverity] = useState<1|2|3|4|5>(3);
  const [newTrigger, setNewTrigger] = useState(TRIGGERS[0]);
  const [newNotes, setNewNotes] = useState('');

  const handleSave = () => {
    if (editingIncident) {
      updateIncident({ ...editingIncident, trigger: newTrigger, severity: newSeverity, notes: newNotes });
      setEditingIncident(null);
    } else {
      addIncident({
        id: Math.random().toString(),
        date: new Date().toISOString(),
        trigger: newTrigger,
        severity: newSeverity,
        notes: newNotes,
        petId: petId ?? undefined,
      });
      // Prompt review after 5th log entry (positive milestone)
      const newCount = incidents.length + 1;
      if (newCount === 5 && shouldPromptReview(1)) {
        markReviewPrompted();
        setTimeout(requestAppReview, 1500);
      }
    }
    setShowAddModal(false);
    setNewSeverity(3);
    setNewTrigger(TRIGGERS[0]);
    setNewNotes('');
  };

  const handleEdit = (incident: Incident) => {
    setEditingIncident(incident);
    setNewTrigger(incident.trigger);
    setNewSeverity(incident.severity);
    setNewNotes(incident.notes);
    setShowAddModal(true);
  };

  const handleDelete = (id: string) => {
    deleteIncident(id);
  };

  const exportVetReport = () => {
    const doc = new jsPDF();
    const pageW = doc.internal.pageSize.getWidth();

    // Header
    doc.setFontSize(20);
    doc.setTextColor(91, 138, 114); // primary sage green
    doc.text('PetCalm — Behavior Report', 20, 22);

    doc.setFontSize(10);
    doc.setTextColor(93, 109, 126);
    doc.text(`Patient: ${petName}`, 20, 32);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, 20, 39);
    doc.text(`Total incidents recorded: ${incidents.length}`, 20, 46);

    // Divider
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 51, pageW - 20, 51);

    // Table header
    let y = 60;
    doc.setFontSize(9);
    doc.setTextColor(44, 62, 80);
    doc.setFont('helvetica', 'bold');
    doc.text('Date', 20, y);
    doc.text('Trigger', 55, y);
    doc.text('Severity', 115, y);
    doc.text('Notes', 145, y);
    doc.setFont('helvetica', 'normal');
    y += 5;
    doc.line(20, y, pageW - 20, y);
    y += 6;

    incidents.forEach((incident) => {
      if (y > 270) {
        doc.addPage();
        y = 20;
      }
      doc.setFontSize(8);
      doc.setTextColor(44, 62, 80);
      doc.text(new Date(incident.date).toLocaleDateString(), 20, y);
      doc.text(incident.trigger, 55, y);
      // Color-code severity
      const sev = incident.severity;
      doc.setTextColor(sev >= 4 ? 231 : sev === 3 ? 243 : 39, sev >= 4 ? 76 : sev === 3 ? 156 : 174, sev >= 4 ? 60 : sev === 3 ? 18 : 96);
      doc.text(`${sev}/5`, 115, y);
      doc.setTextColor(44, 62, 80);
      if (incident.notes) {
        const noteLines = doc.splitTextToSize(incident.notes, 50);
        doc.text(noteLines[0], 145, y);
      }
      y += 8;
    });

    // Footer
    doc.setFontSize(7);
    doc.setTextColor(160, 160, 160);
    doc.text('Generated by PetCalm — Evidence-based pet anxiety management', 20, 285);

    doc.save(`${petName.replace(/\s+/g, '_')}_behavior_report.pdf`);
  };

  const handleAiAnalysis = async () => {
    setIsAnalyzing(true);
    const result = await getBehaviorAnalysis(incidents, petName);
    setAiAnalysis(result);
    setIsAnalyzing(false);
  };

  // Prepare chart data
  const data = incidents.slice(0, 7).reverse().map(i => ({
    name: new Date(i.date).toLocaleDateString('en-US', { weekday: 'short' }),
    severity: i.severity
  }));

  return (
    <div className="pb-24 pt-6 px-6 h-full flex flex-col">
      <div className="flex justify-between items-center mb-6">
        <h1 className="text-2xl font-bold text-neutral-text">Behavior Log</h1>
        <button onClick={() => setShowAddModal(true)} className="w-10 h-10 bg-primary text-white rounded-full flex items-center justify-center shadow-lg hover:bg-primary-dark transition-colors">
          <Plus size={24} />
        </button>
      </div>

      {/* Chart */}
      {incidents.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-16 text-center">
          <div className="w-20 h-20 bg-primary/10 rounded-full flex items-center justify-center mb-4">
            <span className="text-4xl">📋</span>
          </div>
          <h3 className="text-lg font-bold text-neutral-text mb-2">No incidents logged yet</h3>
          <p className="text-sm text-neutral-subtext mb-6 max-w-xs">Start tracking anxiety incidents to see patterns and get AI-powered insights.</p>
          <Button onClick={() => setShowAddModal(true)} className="flex items-center gap-2">
            <Plus size={18} /> Log First Incident
          </Button>
        </div>
      ) : (<>
      <div className="bg-white p-4 rounded-2xl border border-neutral-100 shadow-sm mb-6 h-48">
        <h3 className="text-xs font-bold text-neutral-subtext uppercase tracking-wider mb-2">Severity Trend (Last 7)</h3>
        <ResponsiveContainer width="100%" height="100%">
          <BarChart data={data}>
            <XAxis dataKey="name" tick={{fontSize: 10}} axisLine={false} tickLine={false} />
            <Tooltip cursor={{fill: 'transparent'}} contentStyle={{borderRadius: '8px', border: 'none', boxShadow: '0 4px 6px -1px rgb(0 0 0 / 0.1)'}} />
            <Bar dataKey="severity" radius={[4, 4, 4, 4]} barSize={20}>
              {data.map((entry, index) => (
                <Cell key={`cell-${index}`} fill={entry.severity > 3 ? '#E74C3C' : '#5B8A72'} />
              ))}
            </Bar>
          </BarChart>
        </ResponsiveContainer>
      </div>

      {/* Action Buttons */}
      <div className="flex gap-3 mb-6">
        {!aiAnalysis && (
          <Button
            variant="accent"
            fullWidth
            onClick={handleAiAnalysis}
            isLoading={isAnalyzing}
            className="flex items-center justify-center gap-2"
          >
            <BrainCircuit size={18} />
            AI Analysis
          </Button>
        )}
        <Button
          variant="ghost"
          fullWidth
          onClick={exportVetReport}
          className="flex items-center justify-center gap-2"
        >
          <FileDown size={18} />
          Export PDF
        </Button>
      </div>

      {/* AI Result Card */}
      {aiAnalysis && (
        <div className="bg-gradient-to-br from-accent-light/20 to-white p-5 rounded-2xl border border-accent/30 mb-6 animate-fade-in">
          <div className="flex items-center gap-2 mb-2 text-accent-dark font-bold">
            <BrainCircuit size={18} />
            <h3>AI Insights</h3>
          </div>
          <p className="text-sm text-neutral-text leading-relaxed whitespace-pre-line">{aiAnalysis}</p>
          <button onClick={() => setAiAnalysis(null)} className="text-xs text-neutral-400 mt-2 underline">Close</button>
        </div>
      )}

      {/* List */}
      <h3 className="text-xs font-bold text-neutral-subtext uppercase tracking-wider mb-3">Recent Incidents</h3>
      <div className="space-y-3">
        {incidents.map(incident => (
          <div key={incident.id} className="bg-white p-4 rounded-xl border border-neutral-100 flex gap-4">
             <div className={`w-12 h-12 rounded-full flex flex-col items-center justify-center text-white font-bold text-sm flex-shrink-0 ${
                incident.severity >= 4 ? 'bg-status-error' : incident.severity === 3 ? 'bg-status-warning' : 'bg-status-success'
             }`}>
                {incident.severity}
             </div>
             <div className="flex-1 min-w-0">
               <div className="flex items-center gap-2">
                 <h4 className="font-bold text-neutral-text">{incident.trigger}</h4>
                 <span className="text-[10px] text-neutral-400">{new Date(incident.date).toLocaleDateString()}</span>
               </div>
               <p className="text-sm text-neutral-subtext mt-1">{incident.notes}</p>
             </div>
             <div className="flex flex-col gap-2 flex-shrink-0">
               <button onClick={() => handleEdit(incident)} className="p-1.5 text-neutral-400 hover:text-primary transition-colors rounded-lg hover:bg-primary/10">
                 <Pencil size={14} />
               </button>
               <button onClick={() => handleDelete(incident.id)} className="p-1.5 text-neutral-400 hover:text-red-500 transition-colors rounded-lg hover:bg-red-50">
                 <Trash2 size={14} />
               </button>
             </div>
          </div>
        ))}
      </div>
      {hasMore && (
        <button
          onClick={loadMore}
          className="mt-4 w-full py-3 rounded-xl border border-neutral-200 text-sm font-semibold text-neutral-subtext hover:text-primary hover:border-primary transition-colors"
        >
          Load More
        </button>
      )}
      </>)}

      {/* Add / Edit Sheet */}
      <BottomSheet
        open={showAddModal}
        onClose={() => { setShowAddModal(false); setEditingIncident(null); setNewSeverity(3); setNewTrigger(TRIGGERS[0]); setNewNotes(''); }}
      >
        {/* Header */}
        <div className="px-6 pb-2 flex-shrink-0">
          <h2 className="text-xl font-bold">{editingIncident ? 'Edit Incident' : 'Log Incident'}</h2>
        </div>

        {/* Scrollable Content */}
        <div className="px-6 py-2 overflow-y-auto flex-1 min-h-0">
          <label className="block text-sm text-neutral-subtext mb-2">Trigger</label>
          <div className="flex flex-wrap gap-2 mb-4">
            {TRIGGERS.map(t => (
              <button
                key={t}
                onClick={() => setNewTrigger(t)}
                className={`px-3 py-1.5 rounded-lg text-xs font-medium border transition-colors ${newTrigger === t ? 'bg-primary text-white border-primary' : 'border-neutral-200 text-neutral-600 hover:border-primary/50'}`}
              >
                {t}
              </button>
            ))}
          </div>

          <label className="block text-sm text-neutral-subtext mb-2">Severity (1-5)</label>
          <div className="px-1 mb-4">
            <input
              type="range" min="1" max="5"
              value={newSeverity}
              onChange={(e) => setNewSeverity(Number(e.target.value) as any)}
              className="w-full accent-primary mb-2 cursor-pointer"
            />
            <div className="flex justify-between text-xs text-neutral-400 font-medium">
              <span>Mild</span><span>Moderate</span><span>Panic</span>
            </div>
          </div>

          <label className="block text-sm text-neutral-subtext mb-2">Notes</label>
          <textarea
            className="w-full border border-neutral-200 rounded-xl p-3 text-sm focus:border-primary focus:ring-2 focus:ring-primary/20 outline-none mb-2 bg-white text-gray-900 resize-none"
            rows={4}
            value={newNotes}
            onChange={(e) => setNewNotes(e.target.value)}
            placeholder="What happened? (Optional)"
          />
        </div>

        {/* Footer */}
        <div className="px-6 pt-4 pb-8 flex-shrink-0 bg-white border-t border-neutral-100">
          <div className="flex gap-3">
            <Button variant="ghost" fullWidth onClick={() => { setShowAddModal(false); setEditingIncident(null); setNewSeverity(3); setNewTrigger(TRIGGERS[0]); setNewNotes(''); }}>Cancel</Button>
            <Button fullWidth onClick={handleSave}>Save Log</Button>
          </div>
        </div>
      </BottomSheet>
    </div>
  );
};